package com.enation.app.shop.core.order.model;

import com.enation.framework.database.PrimaryKeyField;

/**
 * DlyArea generated by MyEclipse - Hibernate Tools
 */

public class DlyArea implements java.io.Serializable {

	private Integer area_id;

	private String name;

	@PrimaryKeyField
	public Integer getArea_id() {
		return area_id;
	}

	public void setArea_id(Integer areaId) {
		area_id = areaId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

    
}